apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32080
  selector:
    app: mskafka-apache
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mskafka-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mskafka-apache
  template:
    metadata:
      labels:
        app: mskafka-apache
        group: web
        tier: frontend
    spec:
      containers:
      - name: mskafka-apache
        image: mskafka_apache
        imagePullPolicy: IfNotPresent          
        ports:
        - containerPort: 80
          name: mskafka-apache
