apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: ms-kafka  
  labels:
    app: apache
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32180
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: ms-kafka  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        group: web
        tier: frontend
    spec:
      containers:
      - name: apache
        image: registry.gitlab.com/mc-b/microservice-kafka/mskafka_apache
        imagePullPolicy: IfNotPresent          
        ports:
        - containerPort: 80
          name: apache
