apiVersion: v1
kind: Service
metadata:
  name: invoicing
  labels:
    app: invoicing
spec:
  ports:
    - port: 8080
  selector:
    app: mskafka-invoicing
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mskafka-invoicing
  labels:
    app: mskafka-invoicing
spec:
  selector:
    matchLabels:
      app: mskafka-invoicing
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mskafka-invoicing
        tier: microservice
    spec:
      containers:
      - name: mskafka-invoicing
        image: mskafka_invoicing
        imagePullPolicy: IfNotPresent    
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
          name: invoicing