apiVersion: v1
kind: Service
metadata:
  name: invoicing
  namespace: ms-kafka  
  labels:
    app: invoicing
spec:
  ports:
    - port: 8080
  selector:
    app: invoicing
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicing
  namespace: ms-kafka  
  labels:
    app: invoicing
spec:
  selector:
    matchLabels:
      app: invoicing
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: invoicing
        tier: microservice
    spec:
      containers:
      - name: invoicing
        image: registry.gitlab.com/mc-b/microservice-kafka/mskafka_invoicing
        imagePullPolicy: IfNotPresent    
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
          name: invoicing
           