apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ms-kafka  
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
    tier: middleware
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: ms-kafka  
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: middleware
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:1.0.0
        imagePullPolicy: IfNotPresent    
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_CREATE_TOPICS
          value: "order:5:1"          
        ports:
        - containerPort: 9092
          name: kafka
