apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: ms-kafka  
  labels:
    app: order
spec:
  ports:
    - port: 8080
  selector:
    app: order
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: order
  namespace: ms-kafka  
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
        tier: microservice
    spec:
      containers:
      - name: order
        image: misegr/mskafka_order
        imagePullPolicy: IfNotPresent    
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
          name: order
         