apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: ms-kafka  
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
    tier: middleware
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: ms-kafka  
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
        tier: middleware
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 2181
          name: zookeeper