apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: mskafka-zookeeper
    tier: middleware
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mskafka-zookeeper
  labels:
    app: mskafka-zookeeper
spec:
  selector:
    matchLabels:
      app: mskafka-zookeeper
      tier: middleware
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mskafka-zookeeper
        tier: middleware
    spec:
      containers:
      - name: mskafka-zookeeper
        image: wurstmeister/zookeeper:3.4.6
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 2181
          name: zookeeper