apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: ms-kubernetes  
  labels:
    app: catalog
spec:
  ports:
    - port: 8080
  selector:
    app: catalog
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: catalog
  namespace: ms-kubernetes  
  labels:
    app: catalog
spec:
  selector:
    matchLabels:
      app: catalog
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalog
        tier: microservice
    spec:
      containers:
      - name: catalog
        image: misegr/microservice-kubernetes-demo-catalog:v0.0.2
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: catalog
        resources:
         limits:
          memory: 400Mi
         requests:
          memory: 100Mi            