apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: ms-kubernetes  
  labels:
    app: apache
    group: web
    tier: frontend
    service: apache
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32280
    name: http
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: ms-kubernetes  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        group: web
        tier: frontend
    spec:
      containers:
      - name: apache
        image: registry.gitlab.com/mc-b/microservice-kubernetes/microservice-kubernetes-demo-apache:v0.0.1
        imagePullPolicy: IfNotPresent          
        ports:
        - containerPort: 80
          name: apache
