apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  ports:
    - port: 8080
  selector:
    app: microservice-kubernetes-demo-catalog
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microservice-kubernetes-demo-catalog
  labels:
    app: microservice-kubernetes-demo-catalog
spec:
  selector:
    matchLabels:
      app: microservice-kubernetes-demo-catalog
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice-kubernetes-demo-catalog
        tier: microservice
    spec:
      containers:
      - name: microservice-kubernetes-demo-catalog
        image: microservice-kubernetes-demo-catalog:0.0.1
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: catalog