apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: ms-rest  
  labels:
    app: catalog
    tier: microservice  
    service: catalog  
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: catalog
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: ms-rest  
  labels:
    app: catalog
    tier: microservice    
spec:
  selector:
    matchLabels:
      app: catalog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalog
        tier: microservice
    spec:
      containers:
      - name: catalog
        image: registry.gitlab.com/mc-b/microservice-kubernetes/microservice-kubernetes-demo-catalog:v0.0.2
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: web
         
