apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: ms-kubernetes  
  labels:
    app: customer
spec:
  ports:
    - port: 8080
  selector:
    app: customer
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: ms-kubernetes  
  labels:
    app: customer
spec:
  selector:
    matchLabels:
      app: customer
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer
        tier: microservice
    spec:
      containers:
      - name: customer
        image: misegr/microservice-kubernetes-demo-customer:v0.0.2
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: customer
         