apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: ms-kubernetes  
  labels:
    app: customer
    tier: microservice 
    service: customer 
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: customer
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: ms-kubernetes  
  labels:
    app: customer
    tier: microservice    
spec:
  selector:
    matchLabels:
      app: customer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer
        tier: microservice
    spec:
      containers:
      - name: customer
        image: registry.gitlab.com/mc-b/microservice-kubernetes/microservice-kubernetes-demo-customer:v0.0.2
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: web
         
