apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard
  labels:
    app: hystrix-dashboard
    group: middleware
    tier: frontend
spec:
  ports:
  - port: 8080
    name: dashboard
  - port: 8989
    name: stream
  clusterIP: None  
  selector:
    app: microservice-kubernetes-demo-hystrix-dashboard
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microservice-kubernetes-demo-hystrix-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-kubernetes-demo-hystrix-dashboard
  template:
    metadata:
      labels:
        app: microservice-kubernetes-demo-hystrix-dashboard
        group: middleware
        tier: frontend
    spec:
      containers:
      - name: microservice-kubernetes-demo-hystrix-dashboard
        image: microservice-kubernetes-demo-hystrix-dashboard:0.0.1
        imagePullPolicy: IfNotPresent          
        ports:
        - containerPort: 8080
          name: dashboard
        - containerPort: 8989
          name: stream          