apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 8080
  selector:
    app: microservice-kubernetes-demo-order
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microservice-kubernetes-demo-order
  labels:
    app: microservice-kubernetes-demo-order
spec:
  selector:
    matchLabels:
      app: microservice-kubernetes-demo-order
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice-kubernetes-demo-order
        tier: microservice
    spec:
      containers:
      - name: microservice-kubernetes-demo-order
        image: microservice-kubernetes-demo-order:0.0.1
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: order