apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: ms-kubernetes  
  labels:
    app: order
    tier: microservice    
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: order
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ms-kubernetes  
  labels:
    app: order
    tier: microservice    
spec:
  selector:
    matchLabels:
      app: order
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
        tier: microservice
    spec:
      containers:
      - name: order
        image: misegr/microservice-kubernetes-demo-order:v0.0.2
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: web
           
