apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ms-kubernetes  
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ms-kubernetes  
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: db
    spec:
      containers:
      - name: postgres
        image: registry.gitlab.com/mc-b/microservice-kubernetes/mskafka_postgres
        imagePullPolicy: IfNotPresent    
        env:
        - name: POSTGRES_PASSWORD
          value: dbpass
        - name: POSTGRES_USER
          value: dbuser
        ports:
        - containerPort: 5432
          name: postgres