apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ms-kubernetes  
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: mskubernetes-postgres
    tier: db
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mskubernetes-postgres
  namespace: ms-kubernetes  
  labels:
    app: mskubernetes-postgres
spec:
  selector:
    matchLabels:
      app: mskubernetes-postgres
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mskubernetes-postgres
        tier: db
    spec:
      containers:
      - name: mskubernetes-postgres
        image: misegr/mskafka_postgres
        imagePullPolicy: IfNotPresent    
        env:
        - name: POSTGRES_PASSWORD
          value: dbpass
        - name: POSTGRES_USER
          value: dbuser
        ports:
        - containerPort: 5432
          name: postgres