apiVersion: v1
kind: Service
metadata:
  name: bpmn-frontend
  labels:
    app: bpmn-frontend
    group: web
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 80  
    protocol: TCP
  selector:
    app: bpmn-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bpmn-frontend
  template:
    metadata:
      labels:
        app: bpmn-frontend
        group: web
        tier: frontend
    spec:
      containers:
      - name: bpmn-frontend
        image: registry.gitlab.com/mc-b/bpmn-tutorial/bpmn-frontend:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 80
          name: bpmn-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bpmn-frontend
  labels:
    app: bpmn-frontend
    tier: frontend  
spec:
  rules:
  - http:
      paths:
      - path: /frontend
        backend:
          serviceName: bpmn-frontend
          servicePort: 80