apiVersion: v1
kind: Service
metadata:
  name: bpmn-backend
  labels:
    app: bpmn-backend
    tier: backend
    group: java
spec:
  ports:
  - port: 8090
    protocol: TCP
  selector:
    app: bpmn-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn-backend
  template:
    metadata:
      labels:
        app: bpmn-backend
        tier: backend
        group: java
    spec:
      containers:        
      - name: bpmn-backend
        image: misegr/bpmn-backend:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8090
          name: bpmn-backend    
        stdin: true 
        tty: true  
           