# Common        
apiVersion: v1
kind: Service
metadata:
  name: common
  namespace: scsesi
  labels:
    app: common
    group: ewolff-scsesi
    tier: frontend
spec:
  ports:
  - port: 8080
  selector:
    app: common
  clusterIP: None        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: scsesi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
        group: ewolff-scsesi
        tier: frontend
    spec:
      containers:
      - name: common
        image: misegr/scsesi_common
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080    
---        
# Order        
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: scsesi
  labels:
    app: order
    group: ewolff-scsesi
    tier: frontend
spec:
  ports:
  - port: 8080
  selector:
    app: order
  clusterIP: None        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: scsesi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        group: ewolff-scsesi
        tier: frontend
    spec:
      containers:
      - name: order
        image: misegr/scsesi_order
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080    
---        
# Varnish Server
apiVersion: v1
kind: Service
metadata:
  name: varnish
  namespace: scsesi
  labels:
    app: varnish
    group: ewolff-scsesi
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32080
    protocol: TCP
  selector:
    app: varnish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scsesi-varnish
  namespace: scsesi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
        group: ewolff-scsesi
        tier: frontend
    spec:
      containers:
      - name: varnish
        image: misegr/scsesi_varnish
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080

    