# Order        
apiVersion: v1
kind: Service
metadata:
  name: order-standalone
  namespace: scsesi
  labels:
    app: order-standalone
    group: ewolff-scsesi
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32090
  selector:
    app: order-standalone
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: order-standalone
  namespace: scsesi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-standalone
  template:
    metadata:
      labels:
        app: order-standalone
        group: ewolff-scsesi
        tier: frontend
    spec:
      containers:
      - name: order-standalone
        image: misegr/scsesi_order
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080    
           