# Order        
apiVersion: v1
kind: Service
metadata:
  name: order-standalone
  labels:
    app: scsesi-order-standalone
    group: ewolff-scsesi
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32090
  selector:
    app: scsesi-order-standalone
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: scsesi-order-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scsesi-order-standalone
  template:
    metadata:
      labels:
        app: scsesi-order-standalone
        group: ewolff-scsesi
        tier: frontend
    spec:
      containers:
      - name: scsesi-order-standalone
        image: scsesi_order
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080        